import com.bsep_sbz.SIEMCenter.model.sbz.Log;
import com.bsep_sbz.SIEMCenter.model.sbz.enums.LogLevel;
import com.bsep_sbz.SIEMCenter.model.sbz.enums.LogCategory;
import com.bsep_sbz.SIEMCenter.model.sbz.AntivirusLog;

import java.lang.Number;


rule "Neuspesni pokusaji prijave na sistem na istoj masini 2+"
    when
        exists (
            Log(type == LogLevel.ERROR, category == LogCategory.LOGIN, $ha: hostAddress) and
            Number(intValue >= 2) from accumulate(
                            $l: Log(
                                type == LogLevel.ERROR,
                                category == LogCategory.LOGIN,
                                hostAddress == $ha,
                                message.contains("login_successfull:false")
                            ),
                            count($l)
                        )
        )
    then
        System.out.println("Neuspesno logovanje na istu masinu");
end


rule "Neuspesni pokusaji prijave sa istim usernmom 2+"
    when
        exists (
            Log(type == LogLevel.ERROR, category == LogCategory.LOGIN, $s: source) and // source je u ovom slucaju username
            Number(intValue >= 2) from accumulate(
                            $l: Log(
                                type == LogLevel.ERROR,
                                category == LogCategory.LOGIN,
                                source == $s,
                                message.contains("login_successfull:false")
                            ),
                            count($l)
                        )
        )
    then
        System.out.println("Neuspesno logovanje sa istim usernamom");
end


rule "Pojava loga ciji tip je ERROR"
    when
        Log(type == LogLevel.ERROR)
    then
        System.out.println("Pronadjen je Error Log");
end


rule "Pokusaj prijave na nalog koji nije bio aktivan 90+ dana"
    when
        Log(category == LogCategory.LOGIN, $s: source, $ts: timestamp) // source je u ovom slucaju username
        Number(Log.getDaysOfInactivity(longValue, $ts.getTime()) >= 90) from accumulate(
                                    $l: Log(
                                        category == LogCategory.LOGIN,
                                        source == $s,
                                        timestamp != $ts,
                                        $ts2: timestamp //,
                                        //message.contains("login_successfull:false")
                                    ),
                                    max($ts2.getTime())
                                )
    then
        System.out.println("Nije bio aktivan 90+ dana");
end

/*rule "Pojava loga u kome antivirus registruje pretnju, a da u roku od 1h se ne generise log o uspesnom eliminisanju pretnje"
    when
            $al: AntivirusLog(logLevel == LogLevel.ERROR, $ts: timestamp)
            AntivirusLog(logLevel == LogLevel.INFO, relatedLog != null, relatedLog == $al , AntivirusLog.diffrenceInHours($al.timestamp, timestamp) <= 1 )

    then
        System.out.println("Nije se generisao log o uspesnom eliminisanju pretnje");
end*/