

scan-logs:
  # lista monitoring elemenata (foldera i fajlova) koji ce biti posmatrani
  monitoring-elements:
    -
      path: C:\Windows\System32\winevt\Logs
      includesFiles:
        - Setup.*
      excludesFiles: []
      # lista regex-a koji ce se koristiti pri filtriranju logova
      includes: []
      # lista regex-a - ovde ce biti filtrirani logovi koji su prosli filtriranje po includes regex-ima (regexi su razdvojeni zarezom)
      excludes:
        - .*Event ID:\s*1.*
    -
      path: ./SIEM/LogSimulator/Logs/Logs_11.05.2019.txt
      # Posto je zadata putanja bas do fajla, a ne foldera, onda ne smemo imati property-je includesFiles i excludesFiles
      # includesFiles: []
      # excludesFiles: []
      # lista regex-a koji ce se koristiti pri filtriranju logova
      includes:
        - .*TRACE.*
        - .*WARN.*
      # lista regex-a - ovde ce biti filtrirani logovi koji su prosli filtriranje po includes regex-ima (regexi su razdvojeni zarezom)
      excludes:
        - .*OS.*
    -
      path: ./SIEM/LogSimulator/Logs/AntivirusLogs
      includesFiles:
        - Logs.*
      excludesFiles: []
      # lista regex-a koji ce se koristiti pri filtriranju logova
      includes:
        - .*WARN.*
      # lista regex-a - ovde ce biti filtrirani logovi koji su prosli filtriranje po includes regex-ima (regexi su razdvojeni zarezom)
      excludes:
        - .*OS.*
    -
      path: ./SIEM/LogSimulator/Logs/LoginLogs
      includesFiles:
        - .*h@cker.*
      excludesFiles: []
      # lista regex-a koji ce se koristiti pri filtriranju logova
      includes: []
      # lista regex-a - ovde ce biti filtrirani logovi koji su prosli filtriranje po includes regex-ima (regexi su razdvojeni zarezom)
      excludes:
        - .*127\.0\.1\.3.*
    -
      path: ./SIEM/LogSimulator/Logs/OtherLogs
      includesFiles: []
      excludesFiles:
        - .*07.05.2019.*
      # lista regex-a koji ce se koristiti pri filtriranju logova
      includes:
        - .*Transaction.*
        - .*luser123.*
      # lista regex-a - ovde ce biti filtrirani logovi koji su prosli filtriranje po includes regex-ima (regexi su razdvojeni zarezom)
      excludes:
        - .*User from ip address.*

  includes: []
  # globalni regexi - odnose se na sve logove
  # lista regex-a koji ce se koristiti pri filtriranju (regexi su razdvojeni zarezom)

  excludes: []
  # globalni regexi - odnose se na sve logove
  # lista regex-a - ovde ce biti filtrirani logovi koji su prosli filtriranje po includes regex-ima (regexi su razdvojeni zarezom)

  interval: 0
  # u sekundama,
  # ako je vrednost intervala 0, onda se readi o real-time rezimu rada,
  # a ako je vrednost intervala veca od 0, onda se radi o batch rezimu rada