package template_rules;
import com.bsep_sbz.SIEMCenter.model.sbz.enums.log.LogCategory
import com.bsep_sbz.SIEMCenter.model.sbz.log.Alarm;
import com.bsep_sbz.SIEMCenter.model.sbz.log.Log;
query "Get all alarms"
    $a: Alarm()
end

rule "Login attempt rule_0"
    when
        $log: Log($s: source, $h: hostAddress, category == LogCategory.LOGIN,
            message.contains("login_successful:false")) and
        Number(intValue >= 10) from accumulate(
                       $l: Log(
                           hostAddress == $h,
                           this == $log || source != $s,
                           category == LogCategory.LOGIN,
                           message.contains("login_successful:false")
                       ) over window:time(5s),
                       count($l)
                   )
    then
        Alarm alarm = new Alarm();
        alarm.setMessage("Login attempt rule_0");
        alarm.getLogs().add($log);
        insert(alarm);
        System.out.println("Login attempt rule_0");
end


